name: CD Pack
on:
    push:
        branches:
            - "main"
            - "release/*"
jobs:
    Pack:
        needs: Test
        if: github.repository == 'dotnet/Silk.NET'
        runs-on: ubuntu-latest
        steps:
            - name: Pack
              run: dotnet pack -c Release -o ./packages-out/ --version-suffix build${{ github.run_number }}.0
            - name: Push to GitHub Packages
              run: dotnet nuget push ./packages-out/*.nupkg --force-english-output -s https://nuget.pkg.github.com/dotnet/index.json -k ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v3
              with:
                  name: packages
                  path: ./packages-out/
